### ISSUE TITLE
mktrayicon terminates after few seconds in minimal environment

### ISSUE THREAD

**Issue by bdantas** [jonhoo/mktrayicon#7]
mktrayicon works perfectly in my daily driver OS (Tiny Core Linux with Xorg, fluxbox, and several gtk3 apps installed).

Today I packaged mktrayicon so that other Tiny Core Linux users can enjoy it, so I decided to see what would happen if I ran mktrayicon in Tiny Core Linux with **nothing but** Xorg, fluxbox, and gtk3 (and its dependencies) installed. Test command was `mktrayicon -i /path/to/custom/icon.png -t "hello world"`

Icon and tooltip show up just fine but, strangely, after a few seconds (anywhere from 4 to 10 seconds in my tests) the terminal says "Terminated" and icon disappears. No errors of any kind show up in the terminal. mktrayicon just quietly and mysteriously terminates for no apparent reason. 

Running `ldd /usr/local/bin/mktrayicon` in the minimal environment shows that all shared libraries that mktrayicon is linked to are present. Maybe there is a hidden dependency? Does mktrayicon depend on anything other than X, gtk3, some sort of panel, and the shared libraries it is linked to?

**Comment by jonhoo** [comment]
Hmm, no, I don't expect it to depend on anything else. Maybe try adding some prints to see what causes it to terminate?

**Comment by bdantas** [comment]
Gosh, when setting up the minimal environment I forgot to disable my personal startup scripts. One of my scripts was the culprit. (There is no wifi connection in the minimal environment, one of my startup scripts starts/kills mktrayicon instance showing wifi.png as appropriate, and, alas, the icon I randomly chose for testing was wifi.png. Classic Swiss cheese situation.)

I'm terribly sorry for the noise. If there is X, gtk3, and a panel, `mktrayicon` works exactly as advertised.
